"""
sample_data.py
Pre-configured sample documents for instant testing, demonstration, and evaluation of StructraMorph.ai.
Features hierarchical font sizes, titles, sub-titles, main contents, sub-contents (bullets), tabulations, and visual images.
"""
from typing import Dict, List, Tuple
from .models import Block, BlockType, Document

SAMPLE_DOCUMENTS: Dict[str, Tuple[Document, List[Block]]] = {
    "architecture": (
        Document(
            id="doc-sample-architecture",
            filename="StructraMorph_Architecture_Spec.pdf",
            content_type="application/pdf",
            page_count=2,
            status="parsed",
        ),
        [
            Block(
                id="block-arch-1",
                doc_id="doc-sample-architecture",
                order=0,
                type=BlockType.TITLE,
                content="StructraMorph.ai: Autonomous Document Parsing & Component Segmentation",
                original_content="StructraMorph.ai: Autonomous Document Parsing & Component Segmentation",
                font_size=24.0,
                page=1,
                confidence=0.99,
            ),
            Block(
                id="block-arch-2",
                doc_id="doc-sample-architecture",
                order=1,
                type=BlockType.MAIN_HEADING,
                content="1. Executive Abstract & System Overview",
                original_content="1. Executive Abstract & System Overview",
                font_size=18.0,
                page=1,
                confidence=0.96,
            ),
            Block(
                id="block-arch-3",
                doc_id="doc-sample-architecture",
                order=2,
                type=BlockType.BODY,
                content="Modern enterprise document processing often suffers from monolithic text extraction that discards spatial hierarchy, typography, and tabular geometries. StructraMorph.ai introduces a precision document engineering pipeline that decomposes raw PDFs, Word documents, scanned imagery, and unstructured prose into an interactive component graph. Each element—titles, multi-tier headers, body narratives, footers, and tabulations—becomes an independently addressable semantic node.",
                original_content="Modern enterprise document processing often suffers from monolithic text extraction that discards spatial hierarchy, typography, and tabular geometries. StructraMorph.ai introduces a precision document engineering pipeline that decomposes raw PDFs, Word documents, scanned imagery, and unstructured prose into an interactive component graph. Each element—titles, multi-tier headers, body narratives, footers, and tabulations—becomes an independently addressable semantic node.",
                font_size=11.0,
                page=1,
                confidence=0.94,
            ),
            Block(
                id="block-arch-3b",
                doc_id="doc-sample-architecture",
                order=3,
                type=BlockType.SUB_CONTENT,
                content="• Micro-granularity: Isolates headings, sentences, tables, and images without token leakage.\n• Word-level LCS Diffing: Real-time visual comparison of additions (+green) and deletions (-red).\n• Vector Recompilation: Generates byte-accurate Word docx and vector PDF exports.",
                original_content="• Micro-granularity: Isolates headings, sentences, tables, and images without token leakage.\n• Word-level LCS Diffing: Real-time visual comparison of additions (+green) and deletions (-red).\n• Vector Recompilation: Generates byte-accurate Word docx and vector PDF exports.",
                font_size=9.5,
                page=1,
                confidence=0.95,
            ),
            Block(
                id="block-arch-img",
                doc_id="doc-sample-architecture",
                order=4,
                type=BlockType.IMAGE,
                content="Figure 1: Extracted Neural Brand & Component Topology",
                original_content="Figure 1: Extracted Neural Brand & Component Topology",
                image_url="/logo.png",
                image_metadata={
                    "width": 640,
                    "height": 640,
                    "format": "PNG",
                    "size_kb": 48.8,
                    "caption": "Extracted architectural hub diagram",
                },
                page=1,
                confidence=1.0,
            ),
            Block(
                id="block-arch-4",
                doc_id="doc-sample-architecture",
                order=5,
                type=BlockType.MAIN_HEADING,
                content="2. Granular Block Classification & NLP Transformation",
                original_content="2. Granular Block Classification & NLP Transformation",
                font_size=18.0,
                page=1,
                confidence=0.95,
            ),
            Block(
                id="block-arch-5",
                doc_id="doc-sample-architecture",
                order=6,
                type=BlockType.SUB_HEADING,
                content="2.1 Target-Scoped Mutation Engine",
                original_content="2.1 Target-Scoped Mutation Engine",
                font_size=14.0,
                page=1,
                confidence=0.92,
            ),
            Block(
                id="block-arch-6",
                doc_id="doc-sample-architecture",
                order=7,
                type=BlockType.BODY,
                content="Rather than sending entire 80-page files across language model boundaries, StructraMorph.ai isolates context boundaries to targeted blocks. Users execute surgical prompts such as tone calibration, structural summarization, or grammar refactoring on isolated elements. A visual diff engine provides immediate word-level diff verification prior to persistence.",
                original_content="Rather than sending entire 80-page files across language model boundaries, StructraMorph.ai isolates context boundaries to targeted blocks. Users execute surgical prompts such as tone calibration, structural summarization, or grammar refactoring on isolated elements. A visual diff engine provides immediate word-level diff verification prior to persistence.",
                font_size=11.0,
                page=1,
                confidence=0.91,
            ),
            Block(
                id="block-arch-7",
                doc_id="doc-sample-architecture",
                order=8,
                type=BlockType.MAIN_HEADING,
                content="3. Tabulation Benchmarks & Latency Matrix",
                original_content="3. Tabulation Benchmarks & Latency Matrix",
                font_size=18.0,
                page=2,
                confidence=0.97,
            ),
            Block(
                id="block-arch-8",
                doc_id="doc-sample-architecture",
                order=9,
                type=BlockType.TABLE,
                content="",
                original_content="",
                table_data=[
                    ["Document Ingestion Modality", "Parser Pipeline", "Segmentation Latency (ms)", "F1 Classification Score"],
                    ["Native PDF (Vector + Text)", "pdfplumber + Layout Heuristic", "184 ms", "98.4%"],
                    ["Office OpenXML (.docx)", "python-docx Tree Walker", "62 ms", "99.2%"],
                    ["Scanned TIFF / High-Res PNG", "Tesseract OCR + Spatial Bounding", "840 ms", "94.6%"],
                    ["Unstructured Markdown / Raw Text", "Regex Pattern Analyzer", "12 ms", "99.8%"],
                ],
                original_table_data=[
                    ["Document Ingestion Modality", "Parser Pipeline", "Segmentation Latency (ms)", "F1 Classification Score"],
                    ["Native PDF (Vector + Text)", "pdfplumber + Layout Heuristic", "184 ms", "98.4%"],
                    ["Office OpenXML (.docx)", "python-docx Tree Walker", "62 ms", "99.2%"],
                    ["Scanned TIFF / High-Res PNG", "Tesseract OCR + Spatial Bounding", "840 ms", "94.6%"],
                    ["Unstructured Markdown / Raw Text", "Regex Pattern Analyzer", "12 ms", "99.8%"],
                ],
                page=2,
                confidence=0.98,
            ),
            Block(
                id="block-arch-9",
                doc_id="doc-sample-architecture",
                order=10,
                type=BlockType.BODY,
                content="The tabulation engine ensures zero loss of dimensional fidelity during export. Edits made in the browser-based grid synchronize seamlessly into Word docx and vector PDF tables with custom cell padding, alternating fills, and automatic column scaling.",
                original_content="The tabulation engine ensures zero loss of dimensional fidelity during export. Edits made in the browser-based grid synchronize seamlessly into Word docx and vector PDF tables with custom cell padding, alternating fills, and automatic column scaling.",
                font_size=11.0,
                page=2,
                confidence=0.93,
            ),
            Block(
                id="block-arch-10",
                doc_id="doc-sample-architecture",
                order=11,
                type=BlockType.FOOTER,
                content="StructraMorph.ai Architecture Group · Confidential · Page 2 of 2",
                original_content="StructraMorph.ai Architecture Group · Confidential · Page 2 of 2",
                font_size=8.5,
                page=2,
                confidence=0.99,
            ),
        ],
    ),
    "financial": (
        Document(
            id="doc-sample-financial",
            filename="Q3_Enterprise_Financial_Review.docx",
            content_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            page_count=1,
            status="parsed",
        ),
        [
            Block(
                id="block-fin-1",
                doc_id="doc-sample-financial",
                order=0,
                type=BlockType.TITLE,
                content="OmniCorp Global Financial & Operational Review — Q3",
                original_content="OmniCorp Global Financial & Operational Review — Q3",
                font_size=23.0,
                page=1,
                confidence=0.99,
            ),
            Block(
                id="block-fin-2",
                doc_id="doc-sample-financial",
                order=1,
                type=BlockType.MAIN_HEADING,
                content="Strategic Executive Summary",
                original_content="Strategic Executive Summary",
                font_size=17.5,
                page=1,
                confidence=0.97,
            ),
            Block(
                id="block-fin-3",
                doc_id="doc-sample-financial",
                order=2,
                type=BlockType.BODY,
                content="OmniCorp concluded the third quarter with record gross margins of 68.4%, outpacing baseline street estimates by 320 basis points. Revenue acceleration was primarily propelled by cloud modernization contracts across North America and EMEA, offsetting macroeconomic headwinds in the Asia-Pacific retail segment.",
                original_content="OmniCorp concluded the third quarter with record gross margins of 68.4%, outpacing baseline street estimates by 320 basis points. Revenue acceleration was primarily propelled by cloud modernization contracts across North America and EMEA, offsetting macroeconomic headwinds in the Asia-Pacific retail segment.",
                font_size=11.0,
                page=1,
                confidence=0.95,
            ),
            Block(
                id="block-fin-4",
                doc_id="doc-sample-financial",
                order=3,
                type=BlockType.MAIN_HEADING,
                content="Consolidated Regional Performance Breakdown",
                original_content="Consolidated Regional Performance Breakdown",
                font_size=17.5,
                page=1,
                confidence=0.96,
            ),
            Block(
                id="block-fin-5",
                doc_id="doc-sample-financial",
                order=4,
                type=BlockType.TABLE,
                content="",
                original_content="",
                table_data=[
                    ["Operating Segment", "Q2 Actual ($M)", "Q3 Target ($M)", "Q3 Actual ($M)", "YoY Growth"],
                    ["North America Enterprise", "$142.5M", "$150.0M", "$158.4M", "+18.2%"],
                    ["EMEA Cloud Systems", "$98.2M", "$102.0M", "$106.8M", "+14.6%"],
                    ["APAC Commercial", "$64.1M", "$68.0M", "$63.5M", "+4.2%"],
                    ["LATAM & Emerging", "$22.0M", "$24.0M", "$25.9M", "+22.5%"],
                ],
                original_table_data=[
                    ["Operating Segment", "Q2 Actual ($M)", "Q3 Target ($M)", "Q3 Actual ($M)", "YoY Growth"],
                    ["North America Enterprise", "$142.5M", "$150.0M", "$158.4M", "+18.2%"],
                    ["EMEA Cloud Systems", "$98.2M", "$102.0M", "$106.8M", "+14.6%"],
                    ["APAC Commercial", "$64.1M", "$68.0M", "$63.5M", "+4.2%"],
                    ["LATAM & Emerging", "$22.0M", "$24.0M", "$25.9M", "+22.5%"],
                ],
                page=1,
                confidence=0.99,
            ),
            Block(
                id="block-fin-6",
                doc_id="doc-sample-financial",
                order=5,
                type=BlockType.SUB_HEADING,
                content="Capital Allocation and Forward Guidance",
                original_content="Capital Allocation and Forward Guidance",
                font_size=13.5,
                page=1,
                confidence=0.92,
            ),
            Block(
                id="block-fin-7",
                doc_id="doc-sample-financial",
                order=6,
                type=BlockType.SUB_CONTENT,
                content="• Cloud Capex: $45M earmarked for high-throughput GPU infrastructure.\n• Operating Leverage: Net operating expense reduced by 140 bps quarter-over-quarter.\n• Cash Position: Ending liquidity sits at $310M in unrestricted cash equivalents.",
                original_content="• Cloud Capex: $45M earmarked for high-throughput GPU infrastructure.\n• Operating Leverage: Net operating expense reduced by 140 bps quarter-over-quarter.\n• Cash Position: Ending liquidity sits at $310M in unrestricted cash equivalents.",
                font_size=9.5,
                page=1,
                confidence=0.94,
            ),
            Block(
                id="block-fin-8",
                doc_id="doc-sample-financial",
                order=7,
                type=BlockType.FOOTER,
                content="OmniCorp Investor Relations · Non-GAAP Financial Metrics · Strictly Confidential",
                original_content="OmniCorp Investor Relations · Non-GAAP Financial Metrics · Strictly Confidential",
                font_size=8.0,
                page=1,
                confidence=0.98,
            ),
        ],
    ),
}
